set_clock_groups -asynchronous -group clk_out1_bd_clk_wiz_1_0
set_clock_groups -asynchronous -group clk_out2_bd_clk_wiz_1_0
set_clock_groups -asynchronous -group clk_out3_bd_clk_wiz_1_0
set_clock_groups -asynchronous -group clk_out4_bd_clk_wiz_1_0
